apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: flux
  labels:
    app: sonarqube
  name: sonarqube
spec:
  host: ""
  to:
    kind: Service
    name: sonarqube
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
status:
  ingress:
   - conditions: