apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: sonarqube
  name: sonarqube
spec:
  host: sonarqube-flux.apps.elbit.kbit.ocplab.io
  to:
    kind: Service
    name: sonarqube
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
status:
  ingress:
   - conditions: