apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceName }}_edit
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceName }}