apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jnlpServiceName }}
spec:
  ports:
    - name: agent
      nodePort: 0
      port: 50000
      protocol: TCP
      targetPort: 50000
  selector:
    name: {{ .Values.serviceName }}
  sessionAffinity: None
  type: ClusterIP
