apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  ports:
    - name: web
      nodePort: 0
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: {{ .Values.serviceName }}
  sessionAffinity: None
  type: ClusterIP