apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: sonarqube
  name: sonarqube
spec:
  host: sonarqube-kbit-devops-test.apps.elbit.kbit.ocplab.io
  to:
    kind: Service
    name: sonarqube
    weight: 100
status:
  ingress:
   - conditions: