serviceName: "jenkins"
jnlpServiceName: "jenkins-jnlp"
enableAuth: "false"
memoryLimit: "4Gi"
namespace: "openshift"
disableAdministrativeMonitors: "false"
jenkinsImageStreamTag: "jenkins:2"
jenkinsUcInsecure: "false"
installPlugins: "openshift-client:1.0.32,openshift-sync:1.0.42,sonar:2.9,sonar-quality-gates:1.3.1,workflow-aggregator:2.6"
jenkinsInitImage: "docker.io/dimssss/jenkins-init:0.2"
sonarUiUrl: "replace-me"
bcSyncTragetNs: "replace-me"