apiVersion: argoproj.io/v1alpha1
metadata:
  name: kbit-devops-dev-app
spec:
  destination:
    namespace: kbit-devops-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: infra
    repoURL: 'git@github.com:Dimss/kbit-gitops.git'
    targetRevision: evn/dev
    directory:
      recurse: true
  project: kbit-devops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
