apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-test
  namespace: gitops-infra
spec:
  project: kbit-devops-test
  destination:
    namespace: kbit-devops-test
    server: 'https://kubernetes.default.svc'
  source:
    path: jenkins
    repoURL: 'git@github.com:Dimss/kbit-gitops.git'
    targetRevision: test
    helm:
      parameters:
      - name: "sonarUiUrl"
        value: "http://sonarqube-kbit-devops-test.apps.elbit.kbit.ocplab.io"
      - name: "bcSyncTragetNs"
        value: "kbit-devops-test"
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

