apiVersion: argoproj.io/v1alpha1
metadata:
  name: jenkins
spec:
  destination:
    namespace: kbit-devops-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: jenkins
    repoURL: 'git@github.com:Dimss/kbit-gitops.git'
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
  project: kbit-devops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

